{
 "title": "NGINX Plus",
 "description": "NGINX Plus Prometheus Exporter",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(nginxplus_up, instance)"
    }
   },
   {
    "name": "server_zone",
    "query": {
     "query": "label_values(nginxplus_server_zone_responses, server_zone)"
    }
   },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values(nginxplus_upstream_server_responses, pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_http_requests_total[$__range]))"
    }
   ]
  },
  {
   "title": "Total (2XX from $pod_name pod) requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"2xx\", pod_name=~\"$pod_name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total (3XX from $pod_name pod) requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"3xx\", pod_name=~\"$pod_name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total (4XX from $pod_name pod) requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"4xx\", pod_name=~\"$pod_name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total (5XX from $pod_name pod) requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_upstream_server_responses{code=\"5xx\", pod_name=~\"$pod_name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total (2XX from $server_zone server) requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_server_zone_responses{code=\"2xx\", server_zone=~\"$server_zone\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total (3XX from $server_zone server) requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_server_zone_responses{code=\"3xx\", server_zone=~\"$server_zone\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total (4XX from $server_zone server) requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_server_zone_responses{code=\"4xx\",server_zone=~\"$server_zone\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total (5XX from $server_zone server) requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginxplus_server_zone_responses{code=\"5xx\", server_zone=~\"$server_zone\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total requests rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "requests (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginxplus_http_requests_total{instance=~\"$instance\"}[$__range])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum (irate(nginxplus_http_requests_total{instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "upstream_server_response_time (avg)",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by (upstream) (nginxplus_upstream_server_response_time) <= 500",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginxplus_connections_accepted{instance=~\"$instance\"}[$__range])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "sum(irate(nginxplus_connections_accepted[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginxplus_connections_active{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(nginxplus_connections_active)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "2XX status code rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"2xx\"}[$__range]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "4XX status code rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"4xx\"}[$__range]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  },
  {
   "title": "5XX status code rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (upstream ) (irate(nginxplus_upstream_server_responses{code=\"5xx\"}[$__range]))",
     "legendFormat": "{{ upstream }}"
    }
   ]
  }
 ]
}